import os
import re
import json
from datetime import datetime

# Get script directory
script_dir = os.path.dirname(os.path.abspath(__file__))
blog_dir = script_dir

# Find all html files in blog directory (excluding template.html)
posts = []
for filename in os.listdir(blog_dir):
    if filename.endswith('.html') and filename != 'template.html':
        filepath = os.path.join(blog_dir, filename)
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            
        # Parse JSON-LD
        # Look for <script type="application/ld+json">...</script>
        json_ld_matches = re.findall(r'<script\s+type="application/ld\+json"\s*>(.*?)</script>', content, re.DOTALL)
        post_meta = None
        for match in json_ld_matches:
            try:
                data = json.loads(match.strip())
                # Handle single object or array
                if isinstance(data, list):
                    items = data
                else:
                    items = [data]
                
                for item in items:
                    if item.get('@type') == 'BlogPosting' or item.get('@type') == 'Article':
                        post_meta = item
                        break
            except Exception as e:
                print(f"Warning: Failed to parse JSON-LD in {filename}: {e}")
                
        if not post_meta:
            print(f"Warning: No valid BlogPosting JSON-LD found in {filename}. Skipping.")
            continue
            
        # Extract fields
        post_id = filename[:-5]
        title = post_meta.get('headline', '')
        
        # Date Published
        date_published_str = post_meta.get('datePublished', '')
        # Sort timestamp
        try:
            dt = datetime.strptime(date_published_str, "%Y-%m-%d")
            timestamp = int(dt.timestamp() * 1000)
            formatted_date = dt.strftime("%B %Y")
        except ValueError:
            print(f"Warning: Invalid datePublished format '{date_published_str}' in {filename}. Expected YYYY-MM-DD.")
            timestamp = 0
            formatted_date = date_published_str or "Unknown Date"
            
        # Categories / articleSection
        categories = post_meta.get('articleSection', [])
        if isinstance(categories, str):
            categories = [categories]
        elif not isinstance(categories, list):
            categories = []
            
        # Tags / keywords
        tags = post_meta.get('keywords', [])
        if isinstance(tags, str):
            tags = [t.strip() for t in tags.split(',') if t.strip()]
        elif not isinstance(tags, list):
            tags = []
            
        # Image path resolving
        image_url = post_meta.get('image', '')
        if isinstance(image_url, list) and len(image_url) > 0:
            image_url = image_url[0]
            
        # If absolute, strip domain name
        for domain in ["https://lethaiq.github.io/tql3/", "http://lethaiq.github.io/tql3/", "https://lethaiq.github.io/", "http://lethaiq.github.io/"]:
            if image_url.startswith(domain):
                image_url = image_url[len(domain):]
                break
        
        # If it starts with ../, clean it to be relative to root
        if image_url.startswith('../'):
            image_url = image_url[3:]
            
        # Description
        description = post_meta.get('description', '')
        if not description:
            # Fallback to meta description
            desc_match = re.search(r'<meta\s+name="description"\s+content="(.*?)"', content, re.IGNORECASE)
            if desc_match:
                description = desc_match.group(1)
                
        # Author
        author_data = post_meta.get('author', {})
        if isinstance(author_data, dict):
            author = author_data.get('name', 'Thai Le')
        else:
            author = str(author_data) or 'Thai Le'
            
        posts.append({
            "id": post_id,
            "title": title,
            "date": formatted_date,
            "categories": categories,
            "tags": tags,
            "image": image_url,
            "description": description,
            "url": f"blog/{filename}",
            "timestamp": timestamp,
            "author": author
        })

# Sort posts descending by timestamp
posts.sort(key=lambda x: x['timestamp'], reverse=True)

# Write to posts.js
posts_js_path = os.path.join(blog_dir, 'posts.js')
with open(posts_js_path, 'w', encoding='utf-8') as f:
    f.write("// This file is auto-generated by compile_posts.py. Do not edit manually.\n")
    f.write("window.BLOG_POSTS = ")
    f.write(json.dumps(posts, indent=2))
    f.write(";\n")

print(f"Successfully compiled {len(posts)} blog posts to {posts_js_path}.")
