// This file is auto-generated by compile_posts.py. Do not edit manually.
window.BLOG_POSTS = [
  {
    "id": "welcome",
    "title": "Welcome to 1st post!",
    "date": "June 2026",
    "categories": [
      "News"
    ],
    "tags": [
      "News",
      "Welcome"
    ],
    "image": "",
    "description": "Welcome to the first post of the ARKAI Research Lab blog! We share our latest research insights and news.",
    "url": "blog/welcome.html",
    "timestamp": 1782100800000,
    "author": "Thai Le"
  }
];
