// This file is auto-generated by compile_posts.py. Do not edit manually.
window.BLOG_POSTS = [
  {
    "id": "linguistic-sensitivity-deepfakes",
    "title": "What You Read Isn't What You Hear: Linguistic Sensitivity in Deepfake Speech Detection",
    "date": "June 2026",
    "categories": [
      "Research"
    ],
    "tags": [
      "Research",
      "Audio LM"
    ],
    "image": "images/emnlp25linguisticaudio.png",
    "description": "We investigate how linguistic content affects audio deepfake detection, showing that detectors are highly sensitive to the semantics of spoken text.",
    "url": "blog/linguistic-sensitivity-deepfakes.html",
    "timestamp": 1782100800000,
    "author": "Thai Le"
  },
  {
    "id": "manipulating-web-agents",
    "title": "The Dangers of Indirect Prompt Injection Attacks on LLM-based Web Navigation Agents",
    "date": "August 2025",
    "categories": [
      "Research",
      "News"
    ],
    "tags": [
      "Research",
      "Security"
    ],
    "image": "images/attack-web-agent-logo.png",
    "description": "Exploring security vulnerabilities when autonomous LLM-enabled web agents parse web pages and fall victim to indirect injections via accessibility structures.",
    "url": "blog/manipulating-web-agents.html",
    "timestamp": 1755835200000,
    "author": "Thai Le"
  },
  {
    "id": "turings-echo-gamification",
    "title": "Turing\u2019s Echo: Can You Fool Deepfake Voice Detectors Better Than AI?",
    "date": "May 2025",
    "categories": [
      "Research",
      "Events"
    ],
    "tags": [
      "Research",
      "Speech"
    ],
    "image": "images/turings-echo-logo.webp",
    "description": "We introduce Turing's Echo, a gamified framework that explores deepfake voice detection using crowdsourced feedback and interactive diagnostics.",
    "url": "blog/turings-echo-gamification.html",
    "timestamp": 1747886400000,
    "author": "Thai Le"
  }
];
